//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnMyStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_user
    {
        public int id { get; set; }
        public string real_name { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string sex { get; set; }
        public string email { get; set; }
        public int rank { get; set; }
        public string UpdateRight { get; set; }
        public string DeleteRight { get; set; }
    }
}
