//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnMyStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drink_Order_D
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public Nullable<int> drink_id { get; set; }
        public string drink_name { get; set; }
        public string ice_degree { get; set; }
        public string sweet_degree { get; set; }
        public Nullable<int> drink_no { get; set; }
        public string meno { get; set; }
        public string approved { get; set; }
    }
}
