//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnMyStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavTravelFood
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string HostWords { get; set; }
        public string Price { get; set; }
        public string OpenHours { get; set; }
        public string CreditCard { get; set; }
        public string TravelCard { get; set; }
        public string TrafficGuidelines { get; set; }
        public string ParkingLot { get; set; }
        public string Url { get; set; }
        public string Email { get; set; }
        public string BlogUrl { get; set; }
        public string PetNotice { get; set; }
        public string Reminder { get; set; }
        public string FoodMonths { get; set; }
        public string FoodCapacity { get; set; }
        public string FoodFeature { get; set; }
        public string City { get; set; }
        public string Town { get; set; }
        public string Coordinate { get; set; }
        public string PicURL { get; set; }
    }
}
