//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnMyStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Test
    {
        public int test_id { get; set; }
        public Nullable<System.Guid> test_guid { get; set; }
        public Nullable<System.DateTime> test_time { get; set; }
        public string test_class { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string article { get; set; }
        public string author { get; set; }
        public int hit_no { get; set; }
        public int get_no { get; set; }
        public int email_no { get; set; }
        public string approved { get; set; }
    }
}
