//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnMyStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_ad
    {
        public int ad_id { get; set; }
        public Nullable<System.DateTime> ad_time_start { get; set; }
        public Nullable<System.DateTime> ad_time_end { get; set; }
        public string ad_images { get; set; }
        public string ad_url { get; set; }
    }
}
