//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnMyStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_class
    {
        public int test_class_id { get; set; }
        public string test_class1 { get; set; }
        public string test_class11 { get; set; }
        public string test_class2 { get; set; }
    }
}
