//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnMyStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote_Auto
    {
        public int vote_id { get; set; }
        public Nullable<System.DateTime> Vote_time { get; set; }
        public string title { get; set; }
        public string question_1 { get; set; }
        public int answer_1 { get; set; }
        public string question_2 { get; set; }
        public int answer_2 { get; set; }
        public string question_3 { get; set; }
        public int answer_3 { get; set; }
        public string question_4 { get; set; }
        public int answer_4 { get; set; }
        public string question_5 { get; set; }
        public int answer_5 { get; set; }
        public string question_6 { get; set; }
        public int answer_6 { get; set; }
        public string question_7 { get; set; }
        public int answer_7 { get; set; }
        public string question_8 { get; set; }
        public int answer_8 { get; set; }
        public string question_9 { get; set; }
        public int answer_9 { get; set; }
        public string question_10 { get; set; }
        public int answer_10 { get; set; }
        public int question_all { get; set; }
    }
}
