//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnMyStudy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address_1> Address_1 { get; set; }
        public virtual DbSet<Address_2> Address_2 { get; set; }
        public virtual DbSet<Address_3> Address_3 { get; set; }
        public virtual DbSet<Calendar_Schedule> Calendar_Schedule { get; set; }
        public virtual DbSet<db_user> db_user { get; set; }
        public virtual DbSet<Drink_Order_D> Drink_Order_D { get; set; }
        public virtual DbSet<Drink_Order_M> Drink_Order_M { get; set; }
        public virtual DbSet<Drink_Product> Drink_Product { get; set; }
        public virtual DbSet<FileUpload_DB> FileUpload_DB { get; set; }
        public virtual DbSet<Food_Calorie> Food_Calorie { get; set; }
        public virtual DbSet<Food_Menu> Food_Menu { get; set; }
        public virtual DbSet<News_Test> News_Test { get; set; }
        public virtual DbSet<News_Test_Class> News_Test_Class { get; set; }
        public virtual DbSet<News_Test_Talk> News_Test_Talk { get; set; }
        public virtual DbSet<News_User> News_User { get; set; }
        public virtual DbSet<Question_D1> Question_D1 { get; set; }
        public virtual DbSet<Question_D2> Question_D2 { get; set; }
        public virtual DbSet<Question_M> Question_M { get; set; }
        public virtual DbSet<student_class> student_class { get; set; }
        public virtual DbSet<student_department> student_department { get; set; }
        public virtual DbSet<student_test> student_test { get; set; }
        public virtual DbSet<test> test { get; set; }
        public virtual DbSet<test_class> test_class { get; set; }
        public virtual DbSet<test_only> test_only { get; set; }
        public virtual DbSet<test_talk> test_talk { get; set; }
        public virtual DbSet<test_timestamp> test_timestamp { get; set; }
        public virtual DbSet<test1> test1 { get; set; }
        public virtual DbSet<Vote_1> Vote_1 { get; set; }
        public virtual DbSet<Vote_2> Vote_2 { get; set; }
        public virtual DbSet<Vote_Auto> Vote_Auto { get; set; }
        public virtual DbSet<test_ad> test_ad { get; set; }
    }
}
